### PR TITLE
Minor nits

### PR DESCRIPTION
**Pull request by glensc**
See commit messages for details

### CODE REVIEW

**Comment by petk** [comment]
Partially added via ba9504807b61ce9cbbe1eab1878e2002c7b8db4d and d0f4cf11a10af02faae14f8b335ef6ebe4e23b7d 

More updates on the way in the next patches batch. Thanks for these fixes, @glensc

**Comment by glensc** [comment]
do you cherry pick commits from here and close this? or what?

**Comment by petk** [comment]
Hello, cherry picking them, yes. One more left here about dropping the PHP 7.0... There are multiple branches here - v3.7 v3.8, v3.9, and master.

**Comment by glensc** [comment]
rebased after 09a7c8a

**Comment by glensc** [comment]
three more commits remained, see commit messages for details

**Comment by petk** [comment]
Applied via 87ae1f0105b3482adcf4d0a8243d01bdad10be23 to v3.7 and up branches. I think it should work ok... The errors setting has already been applied via ba9504807b61ce9cbbe1eab1878e2002c7b8db4d

Thank you @glensc :+1:

**Pull request closed without merging**
